<a href="https://colab.research.google.com/github/aniruddhagalgali/bprim_ai/blob/main/20260801_LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import StandardScaler
import joblib

In [16]:
data = pd.read_csv("/content/diabetes_prediction_dataset.csv")
X = data[["age","hypertension","heart_disease","bmi","HbA1c_level","blood_glucose_level"]]
y = data["diabetes"]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train.mean()

np.float64(2.0863311078755942e-16)

In [33]:
p = model.predict_proba(X_test)
print(p)
threshold = 0.5
y_pred = (p>=threshold).astype(int)
y_pred

[[9.99133212e-01 8.66788480e-04]
 [9.99837764e-01 1.62235985e-04]
 [9.99250046e-01 7.49953705e-04]
 ...
 [9.99682630e-01 3.17369576e-04]
 [8.67002649e-01 1.32997351e-01]
 [9.91362049e-01 8.63795139e-03]]


array([[1, 0],
       [1, 0],
       [1, 0],
       ...,
       [1, 0],
       [1, 0],
       [1, 0]])

In [34]:
model = LogisticRegression(max_iter=40)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print (y_pred)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
precision = precision_score(y_test, y_pred)
print(f"Precision: {precision}")
recall = recall_score(y_test, y_pred)
print(f"Recall: {recall}")
f1 = f1_score(y_test, y_pred)
print(f"F1_score: {f1}")

[0 0 0 ... 0 0 0]
Accuracy: 0.95875
Precision: 0.8639736191261336
Recall: 0.6135831381733021
F1_score: 0.7175624786032181
