<a href="https://colab.research.google.com/github/aniruddhagalgali/bprim_ai/blob/main/20260705_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

In [20]:
numbers_list = [2,3,4,5]
numbers_list2 = [5,6,7,8]
numbers_arr = np.array(numbers_list)
numbers_arr2 = np.array(numbers_list2)
print (numbers_arr+numbers_arr2)
print (type (numbers_list))
print (type (numbers_arr))


[ 7  9 11 13]
<class 'list'>
<class 'numpy.ndarray'>


In [66]:
flat_sizes = np.array([650,830,500,1100,940])
prices_lakh = np.array([55.0,72.0,43.8,98.0,85.0])
new_price = prices_lakh * 1.08
registration = np.array([2,2,2,2,2])
total_price = registration + new_price
print (new_price)
print (total_price)
print(flat_sizes[-1])
print(flat_sizes[1:])


[ 59.4    77.76   47.304 105.84   91.8  ]
[ 61.4    79.76   49.304 107.84   93.8  ]
940
[ 830  500 1100  940]


In [44]:
import numpy as np

# 1. Create a 2D Array (Matrix) from nested lists
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# 2. Create a 3D Array (Tensor)
tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])

# 3. Structural placeholders (Rows, Columns)
zeros_field = np.zeros((3, 4))      # 3x4 grid filled with 0.0
ones_field = np.ones((2, 3))        # 2x3 grid filled with 1.0

# 4. Generate and Reshape
reshaped = np.arange(12).reshape(3, 4) # Sequential 0-11 arranged into 3x4
print (tensor.ndim)

3


In [67]:
#Each row is one flat: [size in sq ft, age in years]
flats_table = np.array([[650,8],
                        [820,3],
                        [500,15],
                        [1100,1]])
"""
print(flats_table)
print(flats_table.shape)
print(flats_table.size)
print(flats_table.ndim)
"""

zeros = np.zeros((3,4))
"""
print(zeros)
print(zeros.shape)
print(zeros.size)
print(zeros.ndim)
"""

counting = np.arange(0,10,4)
print(counting)
"""
print(type(counting))
print(counting.shape)
print(counting.size)
print(counting.ndim)
"""


spread = np.linspace(0,10,6)
print(spread)

[0 4 8]
[ 0.  2.  4.  6.  8. 10.]


In [126]:
#Each row is one flat: [size, age, price in lakh]
flats = np.array([[650,8,55],
                        [820,3,72],
                        [500,15,40],
                        [1100,1,98]])

print(flats[1:,2:3])

print ("mean=",np.mean(flats[1:,2:3]))
print ("max=",np.max(flats[1:,2:3]))
print ("min=",np.min(flats[1:,2:3]))
print ("std=",np.std(flats[1:,2:3]))

[[72]
 [40]
 [98]]
mean= 70.0
max= 98
min= 40
std= 23.72059583287626


In [141]:
#Random number generation
i=0
while(i<1):
  i=i+1
  random = np.random.randint(0,256,(2,2))
  print(random)

[[131  96]
 [197 216]]
