<a href="https://colab.research.google.com/github/aniruddhagalgali/bprim_ai/blob/main/20260711_linAlg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

In [10]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])
print("----------------------")
print ("(A*B) matching slots")
print (A*B)
print("----------------------")
print  ("A dot product B")
print (A.dot(B))
print("----------------------")
print  ("A@B row times column")
print (A @ B)
print("----------------------")

----------------------
(A*B) matching slots
[[ 5 12]
 [21 32]]
----------------------
A dot product B
[[19 22]
 [43 50]]
----------------------
A@B row times column
[[19 22]
 [43 50]]
----------------------


In [20]:
A = np.array ([[2,1],[1,3]]) #Capital letter for matrices
b = np.array([50,50]) # Small letter for vectors

prices = np.linalg.solve(A,b)
print ("Samosa price = ", round(prices[0],2))
print ("Chai  price = ", round(prices[1],2))

print (np.allclose((A @ prices),b))


Samosa price =  20.0
Chai  price =  10.0
True
